'use client';
import type {ReactNode} from 'react';
import {UtensilsCrossed,LayoutDashboard,Building2,ReceiptText,MessageSquare,ChefHat,Grid2X2,Users,BookOpen,LogOut,type LucideIcon} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
export const ownerNav:[string,string,LucideIcon][]=[['overview','Overview',LayoutDashboard],['kitchen','Kitchen & orders',ChefHat],['tables','Tables & QR codes',Grid2X2],['menu','Menu items',BookOpen],['staff','Staff',Users],['revenue','Revenue & billing',ReceiptText],['reviews','Customer feedback',MessageSquare]];
export const adminNav:[string,string,LucideIcon][]=[['overview','Overview',LayoutDashboard],['restaurants','Restaurants',Building2],['revenue','Revenue & pendings',ReceiptText],['reviews','Review resolution',MessageSquare]];
export default function WorkspaceShell({admin,section,setSection,logout,children}:{admin:boolean;section:string;setSection:(v:string)=>void;logout:()=>void;children:ReactNode}){
 const nav=admin?adminNav:ownerNav;
 return <div className="classic-workspace"><SidebarProvider><Sidebar className="admin-sidebar"><SidebarHeader><a href="/" className="brand"><span className="brand-icon"><UtensilsCrossed size={20}/></span>TABLE<span>FLOW</span></a><div className="workspace-label">{admin?'PLATFORM WORKSPACE':'RESTAURANT WORKSPACE'}</div><div className="restaurant-picker"><span className="monogram">TF</span><div><strong>{admin?'TABLEFLOW Admin':'Your restaurant'}</strong><small>{admin?'Your restaurant network':'Every table, in flow'}</small></div></div></SidebarHeader><SidebarContent><SidebarMenu>{nav.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={section===id} onClick={()=>setSection(id)}><Icon size={19}/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><button className="workspace-switch" onClick={logout}><LogOut size={18}/>Sign out</button><div className="demo-note"><span>TABLEFLOW<small>Connected restaurant workspace</small></span></div></SidebarFooter></Sidebar><main className="admin-main"><header className="admin-top"><div className="flex items-center gap-3"><SidebarTrigger/><span>{admin?'Platform':'Restaurant'} <span className="muted">/ {nav.find(n=>n[0]===section)?.[1]}</span></span></div><span className="status">Live workspace</span></header><div className="admin-body">{children}</div></main></SidebarProvider></div>
}
