'use client';
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import {Download,Smartphone,Share,Plus,WifiOff,CheckCircle2,ArrowDownToLine} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type InstallEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed'}>};
export default function NativeShell(){
 const [prompt,setPrompt]=useState<InstallEvent|null>(null),[installed,setInstalled]=useState(false),[open,setOpen]=useState(false),[offline,setOffline]=useState(false),[ios,setIos]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{const standalone=window.matchMedia('(display-mode: standalone)');const detect=()=>setInstalled(standalone.matches||!!(navigator as Navigator&{standalone?:boolean}).standalone);detect();setIos(/iPad|iPhone|iPod/.test(navigator.userAgent));setOffline(!navigator.onLine);const capture=(e:Event)=>{e.preventDefault();setPrompt(e as InstallEvent)};const done=()=>{setInstalled(true);setPrompt(null);setOpen(false)};const online=()=>setOffline(false),off=()=>setOffline(true),show=()=>setOpen(true);window.addEventListener('beforeinstallprompt',capture);window.addEventListener('appinstalled',done);window.addEventListener('online',online);window.addEventListener('offline',off);window.addEventListener('tableflow:install',show);standalone.addEventListener('change',detect);if('serviceWorker' in navigator&&window.isSecureContext){navigator.serviceWorker.register('/sw.js',{scope:'/'}).catch(()=>{/* The online app remains available if installation support is blocked. */})}return()=>{window.removeEventListener('beforeinstallprompt',capture);window.removeEventListener('appinstalled',done);window.removeEventListener('online',online);window.removeEventListener('offline',off);window.removeEventListener('tableflow:install',show);standalone.removeEventListener('change',detect)}},[]);
 async function install(){if(!prompt||busy)return;setBusy(true);try{await prompt.prompt();await prompt.userChoice;setPrompt(null)}catch{setPrompt(null);toast.error("Installation could not open. Use your browser’s Add to Home Screen menu.")}finally{setBusy(false)}}
 return <>{offline&&<div className="connection-banner" role="status"><WifiOff size={16}/><span>You’re offline. Reconnect before ordering; check with staff if confirmation is missing.</span></div>}<Dialog open={open} onOpenChange={setOpen}><DialogContent className="tf-dialog install-dialog"><span className="sheet-grabber"/><img className="install-icon" src="/icons/icon-192.png" alt="TABLEFLOW app icon"/><DialogTitle>{installed?'Right at home.':'Your table. One tap away.'}</DialogTitle><DialogDescription>{installed?'You’re using TABLEFLOW in app mode.':'Keep TABLEFLOW on your home screen and open it in its own app window.'}</DialogDescription><div className="install-perks"><span><Smartphone size={19}/>A full-screen dining experience</span><span><CheckCircle2 size={19}/>Your bag stays with you</span><span><ArrowDownToLine size={19}/>No app store download needed</span></div>{installed?<button className="btn full" onClick={()=>setOpen(false)}>Back to TABLEFLOW</button>:prompt?<button className="btn full" disabled={busy} onClick={install}><Download size={18}/>{busy?'Opening installation…':'Install TABLEFLOW'}</button>:<div className="install-steps"><b>{ios?'On iPhone or iPad':'On your Android phone'}</b><p>{ios?'Open this page in Safari, tap Share, then choose Add to Home Screen.':'Open this page in Chrome. Tap the browser menu (⋮), then Install app or Add to Home screen if available.'}</p><small>Using the ChatGPT in-app browser? Open the link in your phone’s browser first. Installation availability depends on the browser.</small></div>}<p className="install-footnote">TABLEFLOW · Orders require an internet connection</p></DialogContent></Dialog></>;
}
export function InstallButton(){return <button className="app-install-button" aria-label="Install TABLEFLOW" onClick={()=>window.dispatchEvent(new Event('tableflow:install'))}><Smartphone size={19}/><span>Get the app</span></button>}
