'use client';
import {useEffect,useRef,useState,type ReactNode,type FormEvent} from 'react';
import {LockKeyhole,UtensilsCrossed} from 'lucide-react';
import {createLogin,verifyLogin,parseLogin,loginKey,type DeviceLogin} from '@/lib/pos-lock';
export default function PosLock({children,onBack}:{children:ReactNode;onBack:()=>void}){
 const [record,setRecord]=useState<DeviceLogin|null>(null),[ready,setReady]=useState(false),[unlocked,setUnlocked]=useState(false),[username,setUsername]=useState(''),[pin,setPin]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[blocked,setBlocked]=useState(false);
 const working=useRef(false),attempts=useRef(0),retryAt=useRef(0);
 useEffect(()=>{try{const raw=localStorage.getItem(loginKey);if(raw)setRecord(parseLogin(raw));const retry=Number(sessionStorage.getItem(loginKey+'-retry'));retryAt.current=Number.isFinite(retry)?retry:0;}catch{setError('Device storage is unavailable or its login is damaged. Restore browser storage before using this workspace.');setBlocked(true)}setReady(true)},[]);
 useEffect(()=>{if(!unlocked)return;let lastActivity=Date.now();const activity=()=>{if(Date.now()-lastActivity>=15*60*1000)setUnlocked(false);else lastActivity=Date.now()};const timer=window.setInterval(()=>{if(Date.now()-lastActivity>=15*60*1000)setUnlocked(false)},15000);window.addEventListener('pointerdown',activity);window.addEventListener('keydown',activity);const changed=(e:StorageEvent)=>{if(e.key===loginKey){setUnlocked(false);try{setRecord(e.newValue?parseLogin(e.newValue):null)}catch{setBlocked(true)}}};window.addEventListener('storage',changed);return()=>{clearInterval(timer);window.removeEventListener('pointerdown',activity);window.removeEventListener('keydown',activity);window.removeEventListener('storage',changed)}},[unlocked]);
 async function submit(e:FormEvent){e.preventDefault();if(working.current||blocked||!ready)return;setError('');if(Date.now()<retryAt.current){setError('Too many attempts. Please wait 30 seconds before trying again.');return}if(!record&&pin!==confirm){setError('The PINs do not match.');return}working.current=true;setBusy(true);try{
 if(!record){const next=await createLogin(username,pin);localStorage.setItem(loginKey,JSON.stringify(next));setRecord(next)}else if(!await verifyLogin(record,username,pin)){attempts.current++;if(attempts.current>=5){retryAt.current=Date.now()+30000;sessionStorage.setItem(loginKey+'-retry',String(retryAt.current));attempts.current=0}setError('Username or PIN is incorrect.');setPin('');return}
 attempts.current=0;retryAt.current=0;sessionStorage.removeItem(loginKey+'-retry');setPin('');setConfirm('');setUnlocked(true);
 }catch{setError('Could not unlock this device. Use a secure browser with storage enabled.')}finally{working.current=false;setBusy(false)}}
 if(unlocked)return <div className="pos-workspace"><div className="pos-lockbar"><span>Local POS · {record?.username}</span><button onClick={()=>{setUnlocked(false);setPin('')}}><LockKeyhole size={16}/>Lock</button></div>{children}</div>;
 return <main className="pos-screen"><section className="pos-card"><div className="pos-mark"><UtensilsCrossed size={26}/></div><p className="eyebrow">TABLEFLOW POS</p><h1>{!ready?'Opening workspace…':record?'Welcome back.':'Set up this POS.'}</h1><p className="muted">{record?'Enter your local username and PIN.':'Choose a username and PIN for this browser’s workspace.'}</p>{ready&&<form className="form" onSubmit={submit}><label>Username<input autoComplete="username" autoCapitalize="none" spellCheck={false} required maxLength={40} value={username} onChange={e=>setUsername(e.target.value)} disabled={busy||blocked}/></label><label>{record?'PIN':'Create PIN (6–12 digits)'}<input type="password" inputMode="numeric" pattern="[0-9]{6,12}" minLength={6} maxLength={12} autoComplete={record?'current-password':'new-password'} required value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} disabled={busy||blocked}/></label>{!record&&<label>Confirm PIN<input type="password" inputMode="numeric" pattern="[0-9]{6,12}" minLength={6} maxLength={12} autoComplete="new-password" required value={confirm} onChange={e=>setConfirm(e.target.value.replace(/\D/g,''))} disabled={busy||blocked}/></label>}{error&&<p role="alert" className="pos-error">{error}</p>}<button className="btn full" disabled={busy||blocked} type="submit">{busy?'Please wait…':record?'Unlock POS':'Save & open POS'}</button></form>}<button className="textbtn" onClick={onBack}>Back to customer menu</button><p className="pos-note">This device only · Locks after 15 minutes of inactivity.<br/>This local lock does not protect cloud data. Keep your PIN safe; clearing browser storage removes the local login and demo data.</p></section></main>;
}
