'use client';
import {useEffect,useRef} from 'react';
import {flushSync} from 'react-dom';
import type {Dispatch,SetStateAction} from 'react';
import {Store,total} from '@/lib/tableflow';
type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
export function useDiningTools(data:Store,setData:Dispatch<SetStateAction<Store>>,ready:boolean){
 const current=useRef({data,ready});current.current={data,ready};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(t:Tool,o:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();
 const register=(t:Tool)=>{try{Promise.resolve(context.registerTool(t,{signal:life.signal})).catch(()=>console.warn('TABLEFLOW structured tools unavailable'))}catch{console.warn('TABLEFLOW structured tools unavailable')}};
 register({name:'read_tableflow_menu',title:'Read TABLEFLOW menu',description:'Read the available dishes in this browser-local TABLEFLOW demo. Does not place an order.',inputSchema:{type:'object',properties:{query:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Expected an object');const a=input as Record<string,unknown>;if(Object.keys(a).some(k=>k!=='query')||(a.query!==undefined&&typeof a.query!=='string'))throw Error('Invalid menu query');if(!current.current.ready)throw Error('Menu is loading');const q=String(a.query||'').toLowerCase();return {mode:'demo',dishes:current.current.data.dishes.filter(d=>d.available&&d.name.toLowerCase().includes(q)).map(({id,name,price,veg,category})=>({id,name,price,veg,category}))}}});
 register({name:'stage_tableflow_bag',title:'Add dishes to demo bag',description:'Add dishes to the visible demo bag. This only stages items; it never places an order or charges money.',inputSchema:{type:'object',properties:{items:{type:'array',minItems:1,maxItems:20,items:{type:'object',properties:{id:{type:'string'},quantity:{type:'integer',minimum:1,maximum:20}},required:['id','quantity'],additionalProperties:false}}},required:['items'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Expected items');const a=input as {items?:unknown};if(Object.keys(a).some(k=>k!=='items')||!Array.isArray(a.items)||a.items.length<1||a.items.length>20)throw Error('Invalid items');const {data:d,ready:r}=current.current;if(!r||!d.visits.some(v=>v.id===d.session&&v.open))throw Error('No active visit');const cart=d.cart.map(i=>({...i}));for(const raw of a.items){if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).some(k=>!['id','quantity'].includes(k)))throw Error('Invalid item');const {id,quantity}=raw as {id:string;quantity:number};if(typeof id!=='string'||!Number.isInteger(quantity)||quantity<1||quantity>20)throw Error('Invalid quantity');const dish=d.dishes.find(x=>x.id===id&&x.available);if(!dish)throw Error('Dish unavailable');const existing=cart.find(x=>x.dishId===id&&x.note==='');if(existing){if(existing.qty+quantity>20)throw Error('Maximum 20 per dish');existing.qty+=quantity}else cart.push({dishId:id,name:dish.name,price:dish.price,qty:quantity,note:''})}flushSync(()=>setData({...d,cart}));return {mode:'demo',items:cart.reduce((s,i)=>s+i.qty,0),subtotal:total(cart),orderPlaced:false}}});return()=>life.abort();
 },[setData]);
}
