// Run with PGLITE_MODULE_ROOT pointing to an installed @electric-sql/pglite package.
// Uses real PostgreSQL in WASM; does not validate remote Realtime or multi-process locking.
import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
const root=process.env.PGLITE_MODULE_ROOT;
if(!root)throw Error('Set PGLITE_MODULE_ROOT to an installed @electric-sql/pglite package');
const {PGlite}=await import(pathToFileURL(root+'/dist/index.js'));
const {pgcrypto}=await import(pathToFileURL(root+'/dist/contrib/pgcrypto.js'));
const db=new PGlite({extensions:{pgcrypto}});
await db.exec('create role anon; create role authenticated;');
await db.exec(readFileSync(new URL('../supabase/002_live_pilot.sql',import.meta.url),'utf8'));
const sql=async(q,args=[])=> (await db.query(q,args)).rows;
const call=async(name,args)=>{const params=args.map((_,i)=>`$${i+1}`).join(',');return (await sql(`select public.${name}(${params}) as value`,args))[0].value};
async function seed(slug){const [{id}]=await sql('select tableflow_pilot.provision($1,$2,$3,$4) as id',[slug,slug,'owner','83726194']);const [{id:dish}]=await sql("insert into tableflow_pilot.menu(restaurant,name,price,category) values($1,'Meal',249,'Meals') returning id",[id]);const {token}=await call('tfp_login',[slug,'owner','83726194']);return {id,dish,token};}
const a=await seed('restaurant-a'),b=await seed('restaurant-b');
const view=await call('tfp_staff',[a.token]);const table=view.tables[0];
await call('tfp_open',[a.token,table.id]);const open=await call('tfp_staff',[a.token]);const visit=open.tables[0].visit;
const guest='a'.repeat(64),other='b'.repeat(64);await call('tfp_join',[table.qr,visit.code,guest]);
const item=()=>JSON.stringify([{id:a.dish,qty:2,price:249,note:'Less spicy'}]);
test('two restaurants cannot read or mutate each other’s tables',async()=>{const otherView=await call('tfp_staff',[b.token]);assert.equal(otherView.name,'restaurant-b');assert.equal(otherView.visits.length,0);await assert.rejects(()=>call('tfp_open',[b.token,table.id]),/unavailable/);await assert.rejects(()=>call('tfp_close',[b.token,visit.id]),/unavailable/);await assert.rejects(()=>call('tfp_staff',['wrong']),/sign in/)});
test('parallel repeat submissions produce one ticket, shared visit supports independent diners',async()=>{const key=crypto.randomUUID();const ids=await Promise.all(Array.from({length:8},()=>call('tfp_order',[guest,key,item()])));assert.equal(new Set(ids).size,1);await call('tfp_join',[table.qr,visit.code,other]);await call('tfp_order',[other,crypto.randomUUID(),item()]);const snapshot=await call('tfp_guest',[guest]);assert.equal(snapshot.orders.length,2);assert.equal(snapshot.orders[0].items[0].price,249);await assert.rejects(()=>call('tfp_status',[b.token,ids[0],'Preparing']),/unavailable/)});
test('server rejects cross-restaurant dishes, price tampering and invalid quantities atomically',async()=>{await sql("update tableflow_pilot.orders set created=now()-interval '3 seconds'");for(const line of [{id:b.dish,qty:1,price:249},{id:a.dish,qty:1,price:1},{id:a.dish,qty:0,price:249},{id:a.dish,qty:1.5,price:249}])await assert.rejects(()=>call('tfp_order',[guest,crypto.randomUUID(),JSON.stringify([line])]));assert.equal((await call('tfp_guest',[guest])).orders.length,2)});
test('status transitions are guarded and close waits until all orders are served',async()=>{await assert.rejects(()=>call('tfp_close',[a.token,visit.id]),/Serve all/);const orders=(await call('tfp_guest',[guest])).orders;await assert.rejects(()=>call('tfp_status',[a.token,orders[0].id,'Served']),/status changed/);for(const o of orders)for(const status of ['Preparing','Ready','Served'])await call('tfp_status',[a.token,o.id,status]);await call('tfp_close',[a.token,visit.id]);assert.ok((await call('tfp_guest',[guest])).closed)});
test('next visit is empty, old codes and tokens cannot order into it',async()=>{await call('tfp_open',[a.token,table.id]);const next=(await call('tfp_staff',[a.token])).tables[0].visit;assert.notEqual(next.id,visit.id);assert.notEqual(next.code,visit.code);const rejected=await call('tfp_join',[table.qr,visit.code,'c'.repeat(64)]);assert.ok(rejected.error);await call('tfp_join',[table.qr,next.code,'c'.repeat(64)]);assert.equal((await call('tfp_guest',['c'.repeat(64)])).orders.length,0);await assert.rejects(()=>call('tfp_order',[guest,crypto.randomUUID(),item()]),/ended/)});
test('login lockout and revocation are enforced on the server',async()=>{for(let i=0;i<5;i++)assert.ok((await call('tfp_login',['restaurant-b','owner','11111111'])).error);assert.match((await call('tfp_login',['restaurant-b','owner','83726194'])).error,/five minutes/);await call('tfp_logout',[b.token]);await assert.rejects(()=>call('tfp_staff',[b.token]),/sign in/)});
test('anonymous SQL role cannot access private tables or provisioning',async()=>{await db.exec('set role anon');try{await assert.rejects(()=>sql('select * from tableflow_pilot.orders'),/permission denied/);await assert.rejects(()=>sql("select tableflow_pilot.provision('x','new','u','12345678')"),/permission denied/);const signals=await sql('select * from public.tfp_signals');assert.deepEqual(Object.keys(signals[0]).sort(),['id','revision']);assert.equal((await call('tfp_menu',[table.qr])).name,'restaurant-a')}finally{await db.exec('reset role')}});
after(()=>db.close());
test('rehearsal bootstrap creates three test tables and generated role credentials',async()=>{await db.exec(readFileSync(new URL('../supabase/003_pilot_rehearsal.sql',import.meta.url),'utf8'));const [record]=await sql('select * from tfp_rehearsal_credentials');const login=await call('tfp_login',['tableflow-rehearsal','manager',record.manager_pin]);assert.ok(login.token);const view=await call('tfp_staff',[login.token]);assert.equal(view.tables.length,3);assert.equal(view.role,'manager');assert.match(view.name,/TEST ORDERS ONLY/);const kitchen=await call('tfp_login',['tableflow-rehearsal','kitchen',record.kitchen_pin]);assert.ok(kitchen.token);assert.equal((await call('tfp_staff',[kitchen.token])).role,'kitchen');assert.equal((await call('tfp_menu',[view.tables[0].qr])).dishes.length,3)});
