'use client';
import {useEffect,useRef,useState,type ReactNode,type FormEvent} from 'react';
import {ArrowUpRight,Building2,CheckCircle2,Clock,MessageSquare,Plus,RefreshCw,Star,Wallet} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import WorkspaceShell,{adminNav,ownerNav} from './workspace-shell';
import OwnerSettings from './owner-settings';
import {Kitchen} from './pilot/app';
import {rpc,RpcError,type Config,type StaffView} from '@/lib/pilot-client';
import {billingTotals,needsAttention,outstanding,invoiceStatus,type Operations,type Restaurant} from '@/lib/operations';
import {money} from '@/lib/tableflow';

export default function OperationsWorkspace({config,token,admin=false,logout,restaurantsPanel}:{config:Config;token:string;admin?:boolean;logout:()=>void;restaurantsPanel?:ReactNode}){
 const [section,setSection]=useState('overview'),[data,setData]=useState<Operations|null>(null),[restaurants,setRestaurants]=useState<Restaurant[]>([]),[role,setRole]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[paymentPending,setPaymentPending]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('attention'),[form,setForm]=useState<Record<string,string>|null>(null);
 const lock=useRef(false);const supported=(config.version||0)>=3;
 async function load(){
  if(!admin){const staff=await rpc<StaffView>(config,'tfp_staff',{p_token:token});setRole(staff.role);if(staff.role!=='manager')return;}
  if(supported)setData(await rpc<Operations>(config,'tfp_operations',{p_token:token,p_admin:admin}));
  if(admin)setRestaurants(await rpc<Restaurant[]>(config,'tfp_admin_restaurants',{p_token:token}));
 }
 useEffect(()=>{void load().catch(e=>setError(e.message))},[config,token,admin]);
 async function act(name:string,args:Record<string,unknown>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await rpc(config,name,{p_token:token,...args});setPaymentPending(false);setForm(null);setNotice('Changes saved.');await load()}catch(e){if(e instanceof RpcError&&!e.uncertain)setPaymentPending(false);setError(e instanceof Error?e.message:'Could not save. Retry your changes.')}finally{lock.current=false;setBusy(false)}}
 function open(kind:string,values:Record<string,string>={}){setError('');setNotice('');setForm({kind,id:crypto.randomUUID(),...values})}
 function field(key:string,value:string){if(paymentPending)return;setForm(f=>f?{...f,[key]:value}:f)}
 function submit(e:FormEvent){e.preventDefault();if(!form)return;const f=form;
  if(f.kind==='credentials')void act('tfp_admin_owner_access',{p_restaurant:f.restaurant,p_staff:f.staff,p_username:f.username,p_password:f.password||''});
  if(f.kind==='invoice')void act('tfp_admin_invoice',{p_restaurant:f.restaurant,p_kind:f.type||'monthly',p_period:f.period,p_due:f.due});
  if(f.kind==='payment'){setPaymentPending(true);void act('tfp_admin_payment',{p_request:f.id,p_invoice:f.invoice,p_amount:Number(f.amount),p_reference:f.reference});}
  if(f.kind==='restaurant')void act('tfp_admin_manage',{p_restaurant:f.restaurant,p_name:f.name,p_active:f.active==='true'});
  if(f.kind==='table')void act('tfp_owner_table',{p_number:Number(f.number),p_enabled:f.enabled!=='false'});
  if(f.kind==='staff')void act('tfp_owner_staff_save',{p_id:f.id,p_username:f.username,p_role:f.role||'waiter',p_active:f.active!=='false',p_password:f.password||''});
  if(f.kind==='review')void act('tfp_resolve_review',{p_id:f.review,p_status:f.status||'in_progress',p_resolution:f.resolution||'',p_admin:admin});
  if(f.kind==='google')void act('tfp_google_review',{p_id:f.id,p_rating:Number(f.rating),p_comment:f.comment||'',p_url:f.url});
 }
 const totals=data?billingTotals(data):null;
 const nav=admin?adminNav:ownerNav;
 const title=section==='overview'?'A good day starts here.':nav.find(n=>n[0]===section)?.[1];
 const filteredReviews=data?.reviews.filter(r=>(filter==='all'||filter==='attention'&&needsAttention(r)||r.status===filter)&&`${r.name} ${r.comment}`.toLowerCase().includes(query.toLowerCase()))||[];
 const input=(key:string,label:string,type='text',required=true)=><label>{label}<input type={type} required={required} value={form?.[key]||''} onChange={e=>field(key,e.target.value)} min={type==='number'?'0.01':undefined} step={type==='number'?'0.01':undefined} maxLength={key==='password'?72:2000}/></label>;
 if(!admin&&role&&role!=='manager')return <Kitchen config={config} token={token} onLogout={logout}/>;
 return <WorkspaceShell admin={admin} section={section} setSection={s=>{if(paymentPending||busy)return;setSection(s);setForm(null);setQuery('')}} logout={logout}>
  <div className="ops-heading"><div><p className="eyebrow">{admin?'THE BIG PICTURE':'MADE FOR YOUR EVERYDAY'}</p><h1>{title}</h1><p className="muted">{admin?'Your restaurants, the numbers, and the people behind them.':'More time for your guests. A little less busywork.'}</p></div><button className="btn secondary" disabled={busy} onClick={()=>{setError('');void load().catch(e=>setError(e.message))}}><RefreshCw size={16}/>Refresh</button></div>
  {error&&<p className="portal-error" role="alert">{error}</p>}{notice&&<p className="portal-success" role="status">{notice}</p>}
  {!supported&&<div className="portal-error">The operations database update is required for billing, feedback, table and staff controls. Existing restaurant and kitchen tools remain available.</div>}
  {section==='overview'&&<><section className="ops-welcome"><div><span className="eyebrow">A LITTLE MORE CLARITY</span><h2>{admin?'Room to grow.\nSpace to focus.':'Great service starts\nbehind the scenes.'}</h2><p>{admin?'Keep every restaurant moving, without losing sight of the details.':'Take care of your team, your tables, and every guest who walks in.'}</p><button onClick={()=>setSection(admin?'restaurants':'kitchen')}> {admin?'Explore restaurants':'Open the kitchen'} <ArrowUpRight size={18}/></button></div><div className="ops-welcome-art" aria-hidden="true"><span>THE DAILY<br/><em>special.</em></span><UtensilMark/></div></section>
  <div className="ops-metrics">{[[Wallet,admin?'Payments received':'Settled sales',data?money(admin?totals!.received:data.sales?.settled||0):'—','All time'],[Clock,admin?'Outstanding invoices':'Open visit bills',data?money(admin?totals!.pending:data.sales?.unsettled||0):'—',admin?'Awaiting payment':'Currently at the tables'],[admin?Building2:CheckCircle2,admin?'Active restaurants':'Available tables',admin?restaurants.filter(r=>r.active).length:data?.tables.filter(t=>t.enabled&&!t.occupied).length??'—',admin?'Across your network':'Ready to welcome guests'],[MessageSquare,'Needs a little care',totals?.flagged??'—','Unresolved reviews · 3 stars or below']].map(([Icon,label,value,caption],i)=>{const MetricIcon=Icon as typeof Wallet;return <article className="ops-metric" key={i}><div><span>{String(label)}</span><MetricIcon size={19}/></div><strong>{String(value)}</strong><small>{String(caption)}</small></article>})}</div>
  <div className="ops-columns"><section className="ops-panel"><div className="between"><h2>Attention, please</h2><span className="ops-dot">Follow-ups</span></div><p className="muted">Small actions that make a difference.</p><button className="ops-action" onClick={()=>setSection('reviews')}><MessageSquare/><span><b>Hear your guests out</b><small>{totals?.flagged??0} low-rating reviews to follow up</small></span><ArrowUpRight/></button><button className="ops-action" onClick={()=>setSection('revenue')}><Wallet/><span><b>Keep payments in view</b><small>Review invoices and recorded receipts</small></span><ArrowUpRight/></button></section><section className="ops-note"><span className="eyebrow">HOSPITALITY, FIRST</span><h2>Behind every rating,<br/>there’s a real person.</h2><p>Listen, leave a thoughtful follow-up note, and close the loop. Good hospitality carries on after the meal.</p><button className="textbtn" onClick={()=>setSection('reviews')}>Visit the feedback desk <ArrowUpRight size={16}/></button></section></div></>}
  {section==='restaurants'&&<>{restaurantsPanel}<section className="ops-panel"><h2>Restaurant controls</h2><input className="ops-search" aria-label="Search restaurants" placeholder="Find a restaurant…" value={query} onChange={e=>setQuery(e.target.value)}/>{restaurants.filter(r=>`${r.name} ${r.slug}`.toLowerCase().includes(query.toLowerCase())).map(r=><div className="ops-row" key={r.id}><span className="ops-initial">{r.name.slice(0,2).toUpperCase()}</span><div><b>{r.name}</b><small>{r.tables} tables</small></div><span className={'ops-pill '+(!r.active?'amber':'')}>{r.active?'Active':'Paused'}</span>{(config.version||0)>=5?r.owners?.map(owner=><button key={owner.id} className="btn secondary" disabled={busy} onClick={()=>open('credentials',{restaurant:r.id,staff:owner.id,username:owner.username})}>Login: {owner.username}</button>):<small>Login controls require database update 008.</small>}<button className="btn secondary" disabled={!supported||busy} onClick={()=>open('restaurant',{restaurant:r.id,name:r.name,active:String(r.active)})}>Manage</button></div>)}</section></>}
  {section==='kitchen'&&<Kitchen config={config} token={token} onLogout={logout}/>}
  {section==='menu'&&<OwnerSettings config={config} token={token}/>}
  {section==='revenue'&&data&&<><div className="ops-metrics"><article className="ops-metric"><span>Payments received</span><strong>{money(totals!.received)}</strong><small>Recorded subscription & setup payments</small></article><article className="ops-metric"><span>Pending balance</span><strong>{money(totals!.pending)}</strong><small>Issued invoices less recorded payments</small></article></div><section className="ops-panel"><div className="between"><h2>Invoices & outstanding balances</h2>{admin&&<button className="btn" disabled={busy||!restaurants.length} onClick={()=>open('invoice',{restaurant:restaurants[0]?.id||'',period:new Date().toISOString().slice(0,7),due:new Date().toISOString().slice(0,10)})}><Plus size={16}/>Raise invoice</button>}</div><p className="muted">{(config.version||0)>=5?'Pending invoices update automatically when this workspace loads or refreshes. Monthly charges start this month; invoices are due after 7 days. Recorded payments reduce the balance.': 'Apply database update 008 to generate pending invoices automatically.'}</p><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Restaurant / period</th><th>Due</th><th>Amount</th><th>Outstanding</th><th>Status</th></tr></thead><tbody>{data.invoices.map(i=><tr key={i.id}><td><b>{i.name}</b><small>{i.kind} · {i.period}</small></td><td>{i.due}</td><td>{money(i.amount)}</td><td>{money(outstanding(i))}<small className={invoiceStatus(i)==='Overdue'?'invoice-overdue':''}>{invoiceStatus(i)}</small></td><td>{outstanding(i)>0?admin?<button className="btn secondary" disabled={busy} onClick={()=>open('payment',{invoice:i.id,amount:String(outstanding(i))})}>Record payment</button>:<span className="ops-pill amber">Pending</span>:<span className="ops-pill">Paid</span>}</td></tr>)}</tbody></table></div>{!data.invoices.length&&<Empty text="No invoices yet. New invoices will appear here."/>}</section><section className="ops-panel"><h2>Payment history</h2>{data.payments.map(p=><div className="ops-row" key={p.id}><Wallet size={20}/><div><b>{p.name}</b><small>{p.reference} · {new Date(p.created).toLocaleDateString()}</small></div><strong>{money(p.amount)}</strong></div>)}{!data.payments.length&&<Empty text="No payments recorded yet."/>}</section></>}
  {section==='reviews'&&data&&<section className="ops-panel"><div className="between"><div><h2>The feedback desk</h2><p className="muted">Ratings of 3 stars or below are automatically flagged for attention.</p></div>{!admin&&<button className="btn secondary" onClick={()=>open('google',{rating:'3'})}><Plus size={16}/>Log Google review</button>}</div><div className="ops-filters"><input aria-label="Search feedback" placeholder="Search feedback or restaurant…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Review status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="attention">Needs attention</option><option value="all">All feedback</option><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option></select></div>{filteredReviews.map(r=><article className="ops-review" key={r.id}><div className="between"><b>{r.name}</b><span className={'ops-pill '+(needsAttention(r)?'amber':'')}>{r.status.replace('_',' ')}</span></div><div className="ops-stars">{Array.from({length:5},(_,i)=><Star key={i} size={15} fill={i<r.rating?'currentColor':'none'}/>)}<small>{r.source==='google'?'Google · manually logged':'Guest feedback'}</small></div><p>{r.comment||'No written comment.'}</p>{r.resolution&&<p className="ops-resolution">Follow-up: {r.resolution}</p>}<div className="between"><small>{new Date(r.created).toLocaleDateString()}</small><button className="btn secondary" disabled={busy} onClick={()=>open('review',{review:r.id,status:r.status,resolution:r.resolution})}>Update follow-up</button></div></article>)}{!filteredReviews.length&&<Empty text="All clear here. No feedback matches this view."/>}</section>}
  {section==='tables'&&data&&<section className="ops-panel"><div className="between"><h2>A place for everyone</h2><button className="btn" onClick={()=>open('table',{number:String(Math.max(0,...data.tables.map(t=>t.number))+1)})}><Plus size={16}/>Add table</button></div><div className="ops-floor">{data.tables.map(t=><article className={'ops-table-card '+(t.occupied?'occupied':'')} key={t.id}><span className="ops-pill">{t.occupied?'Occupied':t.enabled?'Available':'Disabled'}</span><strong>{String(t.number).padStart(2,'0')}</strong><span>TABLE</span><button className="btn secondary" disabled={busy||t.occupied} onClick={()=>open('table',{number:String(t.number),enabled:String(!t.enabled)})}>{t.enabled?'Disable table':'Enable table'}</button></article>)}</div><p className="muted">Print QR codes, open visits and settle bills in Kitchen & orders. Occupied tables cannot be disabled.</p></section>}
  {section==='staff'&&data&&<section className="ops-panel"><div className="between"><div><h2>The people behind the service</h2><p className="muted">Give everyone the access they need.</p></div><button className="btn" onClick={()=>open('staff',{role:'waiter',active:'true'})}><Plus size={16}/>Add teammate</button></div>{data.staff.map(s=><div className="ops-row" key={s.id}><span className="ops-initial">{s.username.slice(0,2).toUpperCase()}</span><div><b>{s.username}{s.self?' (you)':''}</b><small>{s.role} · {s.active?'Active':'Inactive'}</small></div>{s.role!=='manager'&&<button className="btn secondary" disabled={busy} onClick={()=>open('staff',{id:s.id,username:s.username,role:s.role,active:String(s.active),existing:'true'})}>Edit access</button>}</div>)}</section>}
  {supported&&!data&&!error&&section!=='kitchen'&&<p role="status">Loading your workspace…</p>}
  {form&&<Dialog open onOpenChange={open=>{if(!open&&!busy&&!paymentPending)setForm(null)}}><DialogContent className="ops-modal"><DialogTitle>{({credentials:'Restaurant owner login',invoice:'Raise an invoice',payment:'Record a received payment',restaurant:'Manage restaurant',table:'Table settings',staff:'Team access',review:'Follow up with care',google:'Log a Google review'} as Record<string,string>)[form.kind]}</DialogTitle><DialogDescription>Update the details below and save your changes.</DialogDescription><form className="form" onSubmit={submit}><fieldset disabled={busy}>
  {form.kind==='credentials'&&<><label>Owner username<input required pattern="[A-Za-z0-9_.-]{3,40}" maxLength={40} autoComplete="off" value={form.username} onChange={e=>field('username',e.target.value)}/></label><label>New password (optional)<input type="password" autoComplete="new-password" minLength={6} maxLength={72} pattern="(?=.*[A-Za-z])(?=.*[0-9])[A-Za-z0-9]{6,72}" value={form.password||''} onChange={e=>field('password',e.target.value)}/></label><p>Leave blank to keep the password. New passwords need at least 6 characters with letters and numbers only. Saving signs this owner out on all devices. Existing passwords cannot be viewed.</p></>}
  {form.kind==='invoice'&&<><label>Restaurant<select value={form.restaurant} onChange={e=>field('restaurant',e.target.value)}>{restaurants.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Invoice type<select value={form.type||'monthly'} onChange={e=>field('type',e.target.value)}><option value="monthly">Monthly subscription</option><option value="setup">Setup fee</option></select></label>{form.type!=='setup'&&input('period','Billing month','month')}{input('due','Due date','date')}<p>Amount comes from the restaurant’s agreed contract.</p></>}
  {form.kind==='payment'&&<>{input('amount','Amount received (₹)','number')}{input('reference','Bank / cash receipt reference')}<p>This records a payment already received. It does not charge the restaurant.</p></>}
  {form.kind==='restaurant'&&<>{input('name','Restaurant name')}<label>Status<select value={form.active} onChange={e=>field('active',e.target.value)}><option value="true">Active</option><option value="false">Paused</option></select></label><p>Pausing signs staff out. All visits must be closed first.</p></>}
  {form.kind==='table'&&<><label>Table number<input type="number" required min="1" max="100" step="1" value={form.number} onChange={e=>field('number',e.target.value)}/></label><label>Status<select value={form.enabled||'true'} onChange={e=>field('enabled',e.target.value)}><option value="true">Enabled</option><option value="false">Disabled</option></select></label></>}
  {form.kind==='staff'&&<>{input('username','Username')}<label>Role<select value={form.role} onChange={e=>field('role',e.target.value)}><option value="waiter">Waiter — tables & service</option><option value="kitchen">Kitchen — food preparation</option></select></label>{input('password',form.existing?'New password (leave blank to keep)':'Password','password',!form.existing)}<small>At least 6 characters, letters and numbers only. Changing access signs this teammate out.</small><label>Status<select value={form.active} onChange={e=>field('active',e.target.value)}><option value="true">Active</option><option value="false">Inactive</option></select></label></>}
  {form.kind==='review'&&<><label>Status<select value={form.status} onChange={e=>field('status',e.target.value)}><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option></select></label><label>Internal follow-up note<textarea required={form.status==='resolved'} minLength={form.status==='resolved'?3:undefined} maxLength={2000} value={form.resolution} onChange={e=>field('resolution',e.target.value)}/></label><p>Describe what you did to help. This note is internal and is not sent to the guest.</p></>}
  {form.kind==='google'&&<><p>Manually log a review to track its follow-up. Google reviews are not automatically imported.</p><label>Rating<select value={form.rating} onChange={e=>field('rating',e.target.value)}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} stars</option>)}</select></label>{input('url','Google Maps review link','url')}<label>Review text<textarea maxLength={2000} value={form.comment||''} onChange={e=>field('comment',e.target.value)}/></label></>}
  {error&&<p role="alert" className="portal-error">{error}</p>}{paymentPending&&!busy&&<p role="status">Keep this page open. Retry checks the same payment without recording it twice. Details are locked until confirmed.</p>}<div className="ops-modal-actions"><button type="button" className="btn secondary" disabled={paymentPending} onClick={()=>setForm(null)}>Cancel</button><button className="btn">{busy?'Saving…':paymentPending?'Retry same payment':'Save changes'}</button></div></fieldset></form></DialogContent></Dialog>}
 </WorkspaceShell>;
}
function Empty({text}:{text:string}){return <div className="ops-empty"><CheckCircle2 size={28}/><p>{text}</p></div>}
function UtensilMark(){return <div className="ops-plate"><span>✳</span></div>}
