'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {rpc,type Config,type Dish} from '@/lib/pilot-client';
import {money} from '@/lib/tableflow';
type Settings={contract:{billing:string;monthly_amount:number;setup_amount:number;currency:string;owner:string}|null;menu:Dish[]};
type Draft={id:string;name:string;description:string;price:string;category:string;veg:boolean;available:boolean};
export default function OwnerSettings({config,token}:{config:Config;token:string}){
 const [data,setData]=useState<Settings|null>(null),[error,setError]=useState(''),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const lock=useRef(false);
 async function load(){setData(await rpc<Settings>(config,'tfp_owner_settings',{p_token:token}))}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[config,token]);
 async function save(e:FormEvent){e.preventDefault();if(lock.current||!draft)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await rpc(config,'tfp_owner_save_dish',{p_token:token,p_id:draft.id,p_dish:{...draft,price:draft.price}});setDraft(null);setNotice('Menu saved. New orders use the updated price; existing orders keep their original price.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not save. Retry the same dish.')}finally{lock.current=false;setBusy(false)}}
 return <section className="portal"><div className="panel"><h2>Restaurant settings</h2>{error&&<p role="alert" className="portal-error">{error}</p>}{notice&&<p role="status" className="portal-success">{notice}</p>}{data?.contract?<div className="portal-fees"><div>Monthly subscription<strong>{money(data.contract.monthly_amount)}</strong></div><div>One-time setup fee<strong>{money(data.contract.setup_amount)}</strong></div><p className="portal-meta">Assigned by platform admin. These are agreed charges, not payment receipts.</p></div>:<p className="portal-meta">No subscription arrangement has been assigned to this restaurant.</p>}<div className="portal-toolbar" style={{marginTop:24}}><h2>Your menu</h2><button className="btn" disabled={busy} onClick={()=>{setDraft({id:crypto.randomUUID(),name:'',description:'',price:'',category:'',veg:false,available:true});setNotice('')}}>Add dish</button></div>{draft&&<form className="form panel" onSubmit={save}><div className="portal-fields"><label>Dish name<input required maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Category<input required maxLength={50} value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label></div><label>Description<textarea maxLength={500} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Price (₹)<input required type="number" min="0.01" max="999999.99" step="0.01" value={draft.price} onChange={e=>setDraft({...draft,price:e.target.value})}/></label><label className="portal-check"><input type="checkbox" checked={draft.veg} onChange={e=>setDraft({...draft,veg:e.target.checked})}/>Vegetarian</label><label className="portal-check"><input type="checkbox" checked={draft.available} onChange={e=>setDraft({...draft,available:e.target.checked})}/>Available for ordering</label><button className="btn" disabled={busy}>{busy?'Saving…':'Save dish'}</button><button type="button" className="textbtn" disabled={busy} onClick={()=>setDraft(null)}>Cancel</button></form>}{data?.menu.length===0&&<p>No dishes yet. Add and check the real menu before welcoming customers.</p>}{data?.menu.map(d=><article className="portal-restaurant" key={d.id}><div><h3>{d.name}</h3><p>{d.category} · {d.veg?'Vegetarian':'Non-vegetarian'} · {d.available?'Available':'Sold out'}</p><strong>{money(d.price)}</strong></div><button className="btn secondary" disabled={busy} onClick={()=>setDraft({...d,price:String(d.price)})}>Edit dish</button></article>)}</div></section>
}
