'use client';
import {useEffect,useRef,useState} from 'react';
import {ScanLine,UtensilsCrossed,X,Camera} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {tableDestination} from '@/lib/qr';

export default function ScanHome(){
 const [scanning,setScanning]=useState(false),[error,setError]=useState(''),[access,setAccess]=useState(false),[code,setCode]=useState('');
 const video=useRef<HTMLVideoElement>(null),sequence=useRef('');
 useEffect(()=>{let last=0;const key=(e:KeyboardEvent)=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;if(Date.now()-last>5000)sequence.current='';last=Date.now();sequence.current=(sequence.current+e.key).slice(-6);if(sequence.current==='786786')location.assign('/login')};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 useEffect(()=>{if(!scanning)return;let stopped=false,stream:MediaStream|undefined,timer:ReturnType<typeof setTimeout>|undefined;
 const stop=()=>{stopped=true;if(timer)clearTimeout(timer);stream?.getTracks().forEach(t=>t.stop())};
 const start=async()=>{try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera scanning is unavailable here. Use your phone’s Camera app to scan the table QR.');
 const jsQR=(await import('jsqr')).default;stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280}},audio:false});if(stopped){stream.getTracks().forEach(t=>t.stop());return}const v=video.current;if(!v)return;v.srcObject=stream;await v.play();const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)throw Error('Camera scanning is unavailable. Use your phone’s Camera app.');
 const scan=()=>{if(stopped)return;if(v.readyState>=2&&v.videoWidth){const scale=Math.min(1,720/v.videoWidth);canvas.width=Math.round(v.videoWidth*scale);canvas.height=Math.round(v.videoHeight*scale);ctx.drawImage(v,0,0,canvas.width,canvas.height);const frame=ctx.getImageData(0,0,canvas.width,canvas.height);const result=jsQR(frame.data,frame.width,frame.height,{inversionAttempts:'dontInvert'});if(result){const path=tableDestination(result.data,location.origin);if(path){stop();const tableQr=new URL(path,location.origin).searchParams.get('qr');if(tableQr)sessionStorage.removeItem('tfp-guest:'+tableQr);location.assign(path);return}setError('This isn’t a table QR for this TABLEFLOW website. Scan the code printed at your table.')}}timer=setTimeout(scan,220)};scan();
 }catch(e){if(!stopped){setError(e instanceof DOMException&&e.name==='NotAllowedError'?'Camera access is blocked. Allow the camera in browser settings, or scan with your phone’s Camera app.':e instanceof Error?e.message:'Camera could not open. Try your phone’s Camera app.');stream?.getTracks().forEach(t=>t.stop())}}};void start();return stop;
 },[scanning]);
 return <div className="scan-home"><header className="scan-header"><button className="scan-brand" aria-label="TABLEFLOW access" onClick={()=>{setAccess(true);setCode('')}}><UtensilsCrossed size={23}/> TABLE<span>FLOW</span></button><a className="scan-login" href="/login">Restaurant sign in <span>↗</span></a></header><main className="scan-main"><div className="scan-copy"><p className="scan-kicker">PULL UP A CHAIR.</p><h1>Good food.<br/>Great company.<br/><em>Your kind of pace.</em></h1><p className="scan-intro">A little less waiting. A little more enjoying.<br/>Explore the menu, order your favourites, and settle in.</p><button className="scan-button" onClick={()=>{setError('');setScanning(true)}}><ScanLine size={24}/>Scan table QR</button><p className="scan-hint"><Camera size={16}/> Allow camera access when asked</p></div><div className="scan-photo"><img src="/food/biryani.jpg" alt="A freshly prepared meal ready to enjoy"/><div className="scan-photo-label">FRESH FROM THE KITCHEN <span>↗</span></div><div className="scan-photo-caption"><span>A LITTLE LESS WAITING.</span><strong>A little more<br/>enjoying.</strong></div></div></main><section className="scan-steps" aria-label="How it works"><div><span>01</span><h2>Make yourself at home.</h2><p>Scan the QR code at your table.</p></div><div><span>02</span><h2>Find your new favourite.</h2><p>Browse the menu and order at your pace.</p></div><div><span>03</span><h2>Enjoy the good part.</h2><p>Follow your order. We’ll handle the rest.</p></div></section><footer className="scan-footer"><span>Made for moments around the table.</span><span>TABLEFLOW © {new Date().getFullYear()}</span></footer>
 <Dialog open={scanning} onOpenChange={setScanning}><DialogContent className="scan-dialog"><DialogTitle>Scan your table QR</DialogTitle><DialogDescription>Point your camera at the code on your table.</DialogDescription><div className="scan-camera"><video ref={video} muted playsInline autoPlay/><span className="scan-frame" aria-hidden="true"/></div>{error&&<p role="alert" className="pilot-error">{error}</p>}<button className="btn secondary" onClick={()=>setScanning(false)}><X size={16}/>Close camera</button></DialogContent></Dialog>
 <Dialog open={access} onOpenChange={setAccess}><DialogContent className="tf-dialog"><DialogTitle>Access code</DialogTitle><DialogDescription>Enter your access code to continue.</DialogDescription><form className="form" onSubmit={e=>{e.preventDefault();if(code==='786786')location.assign('/login');else setCode('')}}><label>Code<input type="password" inputMode="numeric" autoComplete="off" autoFocus value={code} maxLength={6} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label><button className="btn" disabled={code.length!==6}>Continue</button></form></DialogContent></Dialog>
 </div>
}
