'use client';
import type {ReactNode} from 'react';
import {UtensilsCrossed,LayoutDashboard,Building2,ReceiptText,MessageSquare,ChefHat,Grid2X2,Users,BookOpen,LogOut,ArrowLeft,ArrowUpRight,type LucideIcon} from 'lucide-react';
export const ownerNav:[string,string,LucideIcon][]=[['overview','Home',LayoutDashboard],['kitchen','Kitchen & orders',ChefHat],['tables','Tables & QR',Grid2X2],['menu','Menu items',BookOpen],['staff','My team',Users],['revenue','Revenue & billing',ReceiptText],['reviews','Guest feedback',MessageSquare]];
export const adminNav:[string,string,LucideIcon][]=[['overview','Home',LayoutDashboard],['restaurants','Restaurants',Building2],['revenue','Revenue & pending',ReceiptText],['reviews','Guest feedback',MessageSquare]];
const descriptions:Record<string,string>={dashboard:'Today’s service at a glance',waiter:'Tables, requests & service',biller:'Bills, print layouts & settlement',admin:'Payments, people & permissions',feedback:'Listen and follow up',kitchen:'Orders, preparation & service',tables:'Open tables and print QR codes',menu:'Dishes, prices & availability',staff:'People, roles & access',revenue:'Payments and outstanding balances',reviews:'Listen, follow up & resolve',restaurants:'Manage your restaurant network'};
export default function WorkspaceShell({admin,section,setSection,logout,children,tools}:{tools?:[string,string,LucideIcon][];admin:boolean;section:string;setSection:(v:string)=>void;logout:()=>void;children:ReactNode}){
 const nav=tools||(admin?adminNav:ownerNav);
 const dock=nav.filter(n=>['overview','kitchen','waiter','biller','restaurants','revenue','reviews'].includes(n[0])).slice(0,5);
 return <div className="classic-workspace app-workspace"><header className="app-topbar"><a href="/" className="brand"><span className="brand-icon"><UtensilsCrossed size={20}/></span>TABLE<span>FLOW</span></a><button className="app-signout" onClick={logout}><LogOut size={18}/><span>Sign out</span></button></header><main className="admin-main"><div className="admin-body"><div className="app-location">{section!=='overview'?<button onClick={()=>setSection('overview')}><ArrowLeft size={18}/>Home</button>:<span>{admin?'PLATFORM ADMIN':'MY RESTAURANT'}</span>}<span className="ops-pill">Connected workspace</span></div>{section==='overview'&&<section className="app-launcher" aria-label="Workspace tools">{nav.filter(n=>n[0]!=='overview').map(([id,label,Icon],i)=><button className={`app-tool app-tool-${i%4}`} key={id} onClick={()=>setSection(id)}><span className="app-tool-icon"><Icon size={25}/></span><ArrowUpRight className="app-tool-arrow" size={18}/><strong>{label}</strong><small>{descriptions[id]}</small></button>)}</section>}{children}</div></main><nav className="app-dock" aria-label="Workspace navigation">{dock.map(([id,label,Icon])=><button key={id} aria-current={section===id?'page':undefined} className={section===id?'selected':''} onClick={()=>setSection(id)}><Icon size={21}/><span>{id==='overview'?'Home':id==='reviews'?'Feedback':id==='revenue'?'Payments':id==='kitchen'?'Orders':id==='tables'?'Tables':label}</span></button>)}</nav></div>
}
