'use client';
import GuestFeedback from '@/components/guest-feedback';
import {useEffect,useState,useRef,useCallback,type FormEvent} from 'react';
import {createClient} from '@supabase/supabase-js';
import {UtensilsCrossed,Bell,LayoutDashboard,ArrowUpRight,ShoppingBag,ChefHat,ReceiptText,Plus,Minus,LockKeyhole,RefreshCw,WifiOff,QrCode} from 'lucide-react';
import {Toaster,toast} from 'sonner';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {money} from '@/lib/tableflow';
import OwnerSettings from '@/components/owner-settings';
import {rpc,RpcError,guestToken,sum,bill,stage,readDraft,type Config,type Menu,type Visit,type StaffView,type Dish,type Item,type Pending} from '@/lib/pilot-client';
const steps=['Placed','Preparing','Ready','Served'] as const;
function message(e:unknown){return e instanceof Error?e.message:'Please try again.'}
const tokenKey=(qr:string)=>`tfp-guest:${qr}`;
const draftKey=(qr:string,visit:string)=>`tfp-bag:${qr}:${visit}`;
export default function Pilot(){
 const [config,setConfig]=useState<Config|null>(()=>{
  if(typeof window==='undefined')return null;
  try{
   const saved=localStorage.getItem('tfp-config-cache');
   if(saved){
    const parsed=JSON.parse(saved);
    if(parsed?.url&&parsed?.publishableKey&&parsed?.configured)return parsed as Config;
   }
  }catch{}
  return null;
 }),[bootError,setBootError]=useState(''),[qr,setQr]=useState(''),[staffMode,setStaffMode]=useState(false);
 useEffect(()=>{
  const q=new URLSearchParams(location.search);
  setQr(q.get('qr')||'');
  setStaffMode(q.get('staff')==='1');
  if(q.get('staff')==='1')location.replace('/login');
  fetch('/api/pilot-config').then(r=>{if(!r.ok)throw Error('Could not check the connection.');return r.json()}).then(raw=>{
   const c=raw as Config;
   if(typeof c.url!=='string'||typeof c.publishableKey!=='string'||typeof c.configured!=='boolean')throw Error('Invalid pilot configuration.');
   setConfig(c);
   try{localStorage.setItem('tfp-config-cache',JSON.stringify(c))}catch{}
  }).catch(e=>{if(!config)setBootError(message(e))});
 },[]);
 return <div className="pilot"><Toaster position="top-center" richColors/><header className="pilot-header"><a href="/" className="brand"><span className="brand-icon"><UtensilsCrossed size={20}/></span>TABLE<span>FLOW</span></a><span className="pilot-label">LIVE DINING</span></header>{bootError?<main className="pilot-main"><h1>Connection check failed</h1><p role="alert">{bootError}</p><button className="btn" onClick={()=>location.reload()}>Try again</button></main>:!config?<main className="pilot-main" role="status"><p className="eyebrow">OPENING TABLE</p><h1>Loading your menu…</h1></main>:!config.configured?<Setup config={config}/>:staffMode?<Staff config={config}/>:qr?<Guest config={config} qr={qr}/>:<main className="pilot-main"><p className="eyebrow">WELCOME TO TABLEFLOW</p><h1>Your table starts here.</h1><p>Scan the QR at your table to open the menu. No visit code needed.</p><a className="btn" href="/login">Staff sign in</a><PilotChecklist/></main>}</div>
}
function Setup({config}:{config:Config}){return <main className="pilot-main"><p className="eyebrow">PILOT PREPARATION</p><h1>Ready for setup.</h1><p className="pilot-intro">Live orders are not activated yet. Please ask your waiter for help while the connection is restored.</p><div className="pilot-setup-grid"><section className="panel"><h2>Connection checklist</h2><ol className="pilot-checklist"><li>Supabase project URL received.</li><li>{config.keyPresent?'Publishable key configured.':'Publishable key still required.'}</li><li>{config.setupMessage||'Pilot database migration must be applied and verified.'}</li><li>Create the restaurant’s staff PINs and load its actual menu and prices.</li><li>Check access from the kitchen device and customer phones.</li></ol><a href="/" className="btn secondary">Return to scanner</a></section><PilotChecklist/></div></main>}
function PilotChecklist(){return <section className="panel"><h2>2–3-table trial</h2><p>Run these with test orders before serving guests. Results are pending real-device testing.</p><ol className="pilot-checklist"><li>Use two customer phones and one kitchen device. Open tables 1–3 and print their QR codes.</li><li>Scan with one phone, then another. Verify that the first phone loses access and cannot order.</li><li>Tap Place order repeatedly. Confirm that only one ticket appears.</li><li>Disconnect during submission, reconnect and retry. Confirm exactly one ticket and a clear receipt.</li><li>Close a settled visit. Open a new visit and confirm an empty bag and bill; the old device must no longer be able to order.</li><li>Check cards and buttons on each phone. Aim for tap feedback within 200 ms and kitchen updates within 2 seconds on good Wi-Fi; record actual timings.</li><li>Keep the normal ordering method available. Stop the trial if a ticket is lost, duplicated, sent to another table or billed incorrectly.</li></ol></section>}
function useLive(config:Config,signal:string|undefined,refresh:()=>Promise<void>){
 const latest=useRef(refresh);latest.current=refresh;
 const [state,setState]=useState('Connecting'),[last,setLast]=useState<number|null>(null);
 useEffect(()=>{let active=true,running=false,queued=false;const run=async()=>{if(running){queued=true;return}if(!navigator.onLine){setState('Offline');return}running=true;try{await latest.current();if(active){setLast(Date.now());setState('Connected')}}catch{if(active)setState(navigator.onLine?'Reconnecting':'Offline')}finally{running=false;if(queued&&active){queued=false;void run()}}};void run();const timer=setInterval(()=>{if(document.visibilityState==='visible')void run()},3000);const visible=()=>{if(document.visibilityState==='visible')void run()};const offline=()=>setState('Offline');window.addEventListener('online',run);window.addEventListener('offline',offline);document.addEventListener('visibilitychange',visible);
 const client=signal?createClient(config.url,config.publishableKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}):null;
 const channel=client?.channel(`pilot:${signal}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'tfp_signals',filter:`id=eq.${signal}`},()=>void run()).subscribe(status=>{if(status==='SUBSCRIBED')void run()});
 return()=>{active=false;clearInterval(timer);window.removeEventListener('online',run);window.removeEventListener('offline',offline);document.removeEventListener('visibilitychange',visible);if(channel)void client?.removeChannel(channel)}
 },[config,signal]);return {state,last};
}
function Connection(){return null;}
function Guest({config,qr}:{config:Config;qr:string}){
 const [menu,setMenu]=useState<Menu|null>(null),[visit,setVisit]=useState<Visit|null>(null),[token,setToken]=useState(''),[replaced,setReplaced]=useState(false),[cart,setCart]=useState<Item[]>([]),[pending,setPending]=useState<Pending|null>(null),[tab,setTab]=useState('home'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState('');
 const current=useRef({cart,pending,visit,token});current.current={cart,pending,visit,token};const lock=useRef(false),draftLoaded=useRef(''),storageFailed=useRef(false);
 const applyVisit=useCallback((v:Visit)=>{if(draftLoaded.current!==v.id){try{const d=readDraft(sessionStorage.getItem(draftKey(qr,v.id)));setCart(d.cart);setPending(d.pending);draftLoaded.current=v.id}catch{storageFailed.current=true;setError('Your saved bag could not be read. Keep this page open and contact staff before ordering.')}}setVisit(v)},[qr]);
 const endAccess=useCallback(()=>{setReplaced(true);setVisit(null);setCart([]);setPending(null);current.current={...current.current,visit:null,cart:[],pending:null};draftLoaded.current='';},[]);
 const refresh=useCallback(async()=>{let m:Menu;try{m=await rpc<Menu>(config,'tfp_menu',{p_qr:qr})}catch(e){if(e instanceof RpcError&&!e.uncertain)setError(e.message);throw e}setMenu(m);if(current.current.token&&draftLoaded.current){try{applyVisit(await rpc<Visit>(config,'tfp_guest',{p_token:current.current.token}))}catch(e){if(message(e).includes('TABLE_SESSION_REPLACED'))endAccess();throw e}}},[config,qr,applyVisit,endAccess]);
 const live=useLive(config,menu?.signal,refresh);
 useEffect(()=>{let active=true;if((config.version||0)<4)return;setBusy(true);try{const saved=sessionStorage.getItem(tokenKey(qr));const t=saved||guestToken();if(!saved)sessionStorage.setItem(tokenKey(qr),t);setToken(t);rpc<Visit>(config,'tfp_claim_table',{p_qr:qr,p_guest_token:t}).then(v=>{if(active)applyVisit(v)}).catch(e=>{if(active){if(message(e).includes('TABLE_SESSION_REPLACED'))endAccess();else setError(message(e))}}).finally(()=>{if(active)setBusy(false)})}catch{storageFailed.current=true;setError('Enable browser storage before ordering.');setBusy(false)}return()=>{active=false}},[config,qr,applyVisit,endAccess]);
 function persist(items:Item[],p:Pending|null){const v=current.current.visit;if(!v)return;sessionStorage.setItem(draftKey(qr,v.id),JSON.stringify({cart:items,pending:p}));current.current={...current.current,cart:items,pending:p};setCart(items);setPending(p)}
 function change(d:Dish,n:number){if(lock.current||current.current.pending||visit?.closed)return;try{persist(stage(current.current.cart,d,n),null)}catch(e){toast.error(message(e))}}
 async function join(){if(lock.current||storageFailed.current||replaced)return;lock.current=true;setBusy(true);setError('');try{applyVisit(await rpc<Visit>(config,'tfp_claim_table',{p_qr:qr,p_guest_token:token}))}catch(e){if(message(e).includes('TABLE_SESSION_REPLACED'))endAccess();else setError(message(e))}finally{lock.current=false;setBusy(false)}}
 async function order(){if(lock.current||storageFailed.current||!current.current.visit)return;lock.current=true;setBusy(true);setError('');let p=current.current.pending;try{
 if(!p){if(!current.current.cart.length)return;p={id:crypto.randomUUID(),items:current.current.cart.map(i=>({...i}))};persist(current.current.cart,p)}
 const id=await rpc<string>(config,'tfp_order',{p_token:token,p_request:p.id,p_items:p.items.map(({id,qty,note,price})=>({id,qty,note,price}))});
 try{persist([],null)}catch{storageFailed.current=true;current.current={...current.current,cart:[],pending:null};setCart([]);setPending(null);setError('Order accepted. Browser storage failed; ask staff before ordering again.')}setTab('orders');toast.success(`Kitchen accepted order ${id.slice(0,6).toUpperCase()}`);await refresh().catch(()=>setError('Your order was accepted. Reconnecting to refresh its status…'));
 }catch(e){if(message(e).includes('TABLE_SESSION_REPLACED'))endAccess();if(e instanceof RpcError&&!e.uncertain&&p){try{persist(current.current.cart,null)}catch{}}setError(message(e))}finally{lock.current=false;setBusy(false)}}

 async function requestService(kind:string){if(lock.current||replaced||!visit||visit.closed)return;lock.current=true;setBusy(true);try{await rpc(config,'tfp_service_request',{p_token:token,p_kind:kind});toast.success(kind+' requested. Your waiter has been notified.')}catch(e){setError(message(e))}finally{lock.current=false;setBusy(false)}}
 const receipt=visit?bill(visit):null;
 if((config.version||0)<4)return <main className="pilot-main"><section className="panel"><h1>QR access is being updated.</h1><p>Please ask staff for help. The database needs the new QR session update before code-free entry is available.</p><a href="/" className="btn">Back to scanner</a></section></main>;
 if(replaced)return <main className="pilot-main"><section className="panel session-ended" role="status"><LockKeyhole size={36}/><h1>This table was opened on another device.</h1><p>Your ordering session has ended. Confirmed orders are still with the restaurant; nothing has been cancelled or charged again.</p><a href="/" className="btn">Back to home</a></section></main>;
 return <main className="pilot-main pilot-dining"><div className="pilot-heading"><div><p className="eyebrow">YOUR TABLE</p><h1>{menu?.name||'Loading menu…'}</h1></div>{menu&&<span className="tablebadge">Table {menu.table}</span>}</div>{error&&<p className="pilot-error" role="alert">{error}</p>}{!menu&&<p>If the menu does not load, ask staff to check the connection.</p>}{!visit?<section className="panel pilot-join"><h2>{busy?'Opening your table…':'Your table is almost ready'}</h2><p>No code needed. One device can order at a time.</p>{!busy&&<button className="btn" disabled={!menu||!token||storageFailed.current} onClick={join}>Try opening table again</button>}</section>:visit.closed?<section className="panel"><h2>Thank you for dining with us.</h2><p>This visit is closed. Its bill stays separate from your next meal.</p><a className="btn" href="/">Back to scanner</a></section>:<p className="pilot-visit">Visit {visit.id.slice(0,6).toUpperCase()} · Preparation estimate {menu?.wait} minutes</p>}
 {pending&&<section className="panel pilot-pending"><h2>Order confirmation needed</h2><p>Keep this bag unchanged. Retry to check or complete the same order without sending a duplicate.</p><button className="btn" disabled={busy} onClick={order}>{busy?'Checking order…':'Retry same order'}</button></section>}
 {tab==='home'&&visit&&!visit.closed&&<><section className="dining-welcome"><span>MAKE YOURSELF AT HOME</span><h2>What sounds good?</h2><p>Your table. Everything you need, one tap away.</p></section><section className="app-launcher dining-launcher" aria-label="Table tools">{[['menu','Explore menu','Find your next favourite',UtensilsCrossed],['bag','Your bag',cart.length?money(sum(cart)):'Ready when you are',ShoppingBag],['orders','Track your meal',visit.orders.length+' confirmed orders',ChefHat],['bill','Bill & feedback',receipt?money(receipt.total):'Your table bill',ReceiptText],...((config.version||0)>=6?[['service','Need anything?','Water, cutlery or a helping hand',Bell]]:[])].map(([id,label,detail,Icon],i)=>{const ToolIcon=Icon as typeof ChefHat;return <button key={id as string} className={'app-tool app-tool-'+i} onClick={()=>setTab(id as string)}><span className="app-tool-icon"><ToolIcon size={25}/></span><ArrowUpRight className="app-tool-arrow" size={18}/><strong>{label as string}</strong><small>{detail as string}</small></button>})}</section></>}
 {tab==='service'&&visit&&!visit.closed&&<section className="ops-panel"><h2>A little help at your table</h2><p className="muted">Your requests go straight to the waiter.</p><div className="app-launcher dining-launcher">{['Water','Call waiter','Cutlery','Help with bill'].map((kind,i)=><button key={kind} className={'app-tool app-tool-'+i} disabled={busy} onClick={()=>void requestService(kind)}><Bell size={25}/><strong>{kind}</strong><small>Send request</small></button>)}</div></section>}
 {tab==='menu'&&menu&&<>{menu.dishes.length===0&&<section className="panel"><h2>The menu is being prepared.</h2><p>Please ask your waiter to help you order.</p></section>}<div className="searchbox"><input aria-label="Search live menu" placeholder="Find a dish…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="dishgrid pilot-menu">{menu.dishes.filter(d=>d.name.toLowerCase().includes(search.toLowerCase())).map(d=><article className="dishcard" key={d.id}>{d.image&&<img className="pilot-food" src={d.image} alt={d.name} loading="lazy"/>}<div className="dish-content"><p className="dishmeta">{d.veg?'VEGETARIAN':'NON-VEGETARIAN'} · {d.category}</p><h2 className="dish-name">{d.name}</h2><p>{d.description}</p><div className="between"><strong>{money(d.price)}</strong><button className="addbtn" disabled={!d.available||!visit||!!visit.closed||busy||!!pending||storageFailed.current} onClick={()=>change(d,1)}>{d.available?'Add':'Sold out'}<Plus size={16}/></button></div></div></article>)}</div></>}
 {tab==='bag'&&<section className="panel"><h2>Your bag</h2>{!cart.length?<p>Add dishes from the menu.</p>:<>{cart.map(i=><div className="pilot-bagrow" key={i.id}><div><strong>{i.name}</strong><p>{money(i.price)} each</p><label>Kitchen note<input maxLength={200} value={i.note} disabled={busy||!!pending||!!visit?.closed} onChange={e=>{try{persist(current.current.cart.map(x=>x.id===i.id?{...x,note:e.target.value}:x),null)}catch(error){toast.error(message(error))}}}/></label></div><div className="quantity"><button aria-label={`Remove one ${i.name}`} disabled={busy||!!pending||!!visit?.closed} onClick={()=>change(menu?.dishes.find(d=>d.id===i.id)||{...i,description:'',category:'',veg:false,image:'',available:false},-1)}><Minus size={16}/></button><b>{i.qty}</b><button aria-label={`Add one ${i.name}`} disabled={busy||!!pending||!!visit?.closed||i.qty>=20} onClick={()=>{const d=menu?.dishes.find(d=>d.id===i.id);if(d)change(d,1)}}><Plus size={16}/></button></div></div>)}<div className="between"><strong>Subtotal</strong><strong>{money(sum(cart))}</strong></div><p>Tax is shown on your visit’s final bill.</p><button className="btn full" disabled={busy||!!visit?.closed||!!pending||storageFailed.current} onClick={order}>{busy?'Sending to kitchen…':'Place order'}</button></>}</section>}
 {tab==='orders'&&<section><h2>Your table’s orders</h2>{visit?.orders.length?visit.orders.map(o=><TicketCard key={o.id} ticket={o}/>):<p>No confirmed orders yet.</p>}</section>}
 {tab==='bill'&&<section className="panel"><h2>Your visit’s bill</h2>{visit?.orders.flatMap(o=>o.items).map((i,n)=><div className="orderline" key={n}><span>{i.qty} × {i.name}</span><strong>{money(i.price*i.qty)}</strong></div>)}{receipt&&<><div className="between"><span>Subtotal</span><b>{money(receipt.subtotal)}</b></div><div className="between"><span>Tax ({visit?.tax}%)</span><b>{money(receipt.tax)}</b></div><div className="between grandtotal"><strong>Total</strong><strong>{money(receipt.total)}</strong></div></>}<p>Settle with staff at the counter. Pay at the restaurant; online payment is not available.</p>{visit&&visit.orders.length>0&&<GuestFeedback config={config} token={token}/>}</section>}
 <nav className="pilot-tabs" aria-label="Dining navigation">{[['home','Home',LayoutDashboard],['menu','Menu',UtensilsCrossed],['bag',`Bag (${cart.reduce((s,i)=>s+i.qty,0)})`,ShoppingBag],['orders','Orders',ChefHat],['bill','Bill',ReceiptText]].map(([id,label,Icon])=><button key={id as string} className={tab===id?'selected':''} onClick={()=>setTab(id as string)}><Icon size={21}/>{label as string}</button>)}</nav></main>
}
function TicketCard({ticket,table,onNext,busy}:{ticket:Visit['orders'][number];table?:number;onNext?:()=>void;busy?:boolean}){return <article className="panel pilot-ticket"><div className="between"><strong>{table?`Table ${table} · `:''}#{ticket.id.slice(0,6).toUpperCase()}</strong><span className="status">{ticket.status}</span></div><p className="muted">{new Date(ticket.created).toLocaleTimeString()}</p>{ticket.items.map((i,n)=><div className="orderline" key={n}><span>{i.qty} × {i.name}{i.note&&<small>{i.note}</small>}</span><strong>{money(i.price*i.qty)}</strong></div>)}<div className="between"><b>{money(sum(ticket.items))}</b>{onNext&&<button className="btn" disabled={busy} onClick={onNext}>{busy?'Updating…':ticket.status==='Placed'?'Start preparing':ticket.status==='Preparing'?'Mark ready':'Mark served'}</button>}</div></article>}
function Staff({config}:{config:Config}){return <main className="pilot-main"><a className="btn" href="/login">Sign in with username and password</a></main>}
export function Kitchen({config,token,onLogout}:{config:Config;token:string;onLogout:()=>void}){
 const [data,setData]=useState<StaffView|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[filter,setFilter]=useState('Active'),[settings,setSettings]=useState(false),[codeImage,setCodeImage]=useState<{url:string;image:string;table:number}|null>(null),[close,setClose]=useState<Visit|null>(null);
 const locked=useRef(false),alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 const refresh=useCallback(async()=>{const next=await rpc<StaffView>(config,'tfp_staff',{p_token:token});if(alive.current)setData(next)},[config,token]);const live=useLive(config,data?.signal,refresh);

 async function act(id:string,name:string,args:Record<string,unknown>){if(locked.current)return;locked.current=true;setBusy(id);setError('');try{await rpc(config,name,{p_token:token,...args});await refresh();setClose(null)}catch(e){setError(message(e))}finally{locked.current=false;setBusy('')}}
 async function showQR(qr:string,table:number){if(locked.current)return;locked.current=true;setBusy('qr');try{const {default:QRCode}=await import('qrcode');const url=`${location.origin}/pilot?qr=${qr}`;setCodeImage({url,table,image:await QRCode.toDataURL(url,{width:600,margin:4})})}catch(e){setError(message(e))}finally{locked.current=false;setBusy('')}}
 const tickets=data?.visits.flatMap(v=>v.orders.map(o=>({ticket:o,table:v.table,visit:v.id}))).sort((a,b)=>a.ticket.created.localeCompare(b.ticket.created))||[];
 return <main className="pilot-main pilot-staff"><div className="pilot-heading"><div><p className="eyebrow">LIVE KITCHEN</p><h1>{data?.name||'Loading your restaurant…'}</h1></div><button className="btn secondary" onClick={onLogout}>Lock POS</button></div>{data?.role==='manager'&&(config.version||1)>=2&&<div className="portal-toolbar"><button className="btn secondary" onClick={()=>setSettings(!settings)}>{settings?'Back to kitchen':'Menu & subscription'}</button></div>}{settings&&<OwnerSettings config={config} token={token}/>}<div hidden={settings}>{error&&<p className="pilot-error" role="alert">{error}</p>}{!data&&<p>If this stays disconnected, lock the POS and sign in again after checking the network.</p>}{data&&<><section className="pilot-tables">{data.tables.map(t=>{const v=data.visits.find(v=>v.id===t.visit?.id);return <article className="panel" key={t.id}><div className="between"><h2>Table {t.number}</h2><button className="iconbtn" aria-label={`QR for table ${t.number}`} disabled={!!busy} onClick={()=>showQR(t.qr,t.number)}><QrCode/></button></div>{t.visit?<><span className="status">Visit {t.visit.id.slice(0,6).toUpperCase()}</span><p className="muted">QR access · one ordering device</p>{v&&<p>Bill: <strong>{money(bill(v).total)}</strong></p>}{data.role==='manager'&&v&&<button className="btn secondary" disabled={!!busy} onClick={()=>setClose(v)}>Settle & close visit</button>}</>:<><p>Ready for new diners.</p>{data.role!=='kitchen'&&t.enabled!==false&&<button className="btn" disabled={!!busy} onClick={()=>act(t.id,'tfp_open',{p_table:t.id})}>{busy===t.id?'Opening…':'Open new visit'}</button>}</>}</article>})}</section><div className="pilot-filters">{['Active',...steps,'All'].map(s=><button className={s===filter?'selected':''} key={s} onClick={()=>setFilter(s)}>{s}</button>)}</div><section className="ordergrid">{tickets.filter(({ticket:o})=>filter==='All'||(filter==='Active'?o.status!=='Served':o.status===filter)).map(({ticket,table})=><TicketCard key={ticket.id} table={table} ticket={ticket} busy={!!busy} onNext={ticket.status==='Served'||(data.role==='waiter'&&ticket.status!=='Ready')?undefined:()=>act(ticket.id,'tfp_status',{p_order:ticket.id,p_status:steps[steps.indexOf(ticket.status)+1]})}/>)}</section>{!tickets.length&&<section className="empty"><ChefHat size={36}/><h2>Your kitchen is ready.</h2><p>Confirmed customer orders will appear here.</p></section>}</>}
 </div><Dialog open={!!codeImage} onOpenChange={v=>!v&&setCodeImage(null)}><DialogContent className="tf-dialog"><DialogTitle>Table {codeImage?.table} QR</DialogTitle><DialogDescription>Print this permanent table QR. Scanning opens the table without a code. A new device ends the previous device’s ordering access.</DialogDescription>{codeImage&&<><img className="pilot-qr" src={codeImage.image} alt={`Table ${codeImage.table} QR code`}/><a className="btn" download={`tableflow-pilot-table-${codeImage.table}.png`} href={codeImage.image}>Download QR</a><a className="textbtn" href={codeImage.url} target="_blank" rel="noreferrer">Open customer menu</a></>}</DialogContent></Dialog>
 <Dialog open={!!close} onOpenChange={v=>!v&&setClose(null)}><DialogContent className="tf-dialog"><DialogTitle>Settle table {close?.table}?</DialogTitle><DialogDescription>Confirm that every dish has been served and payment was collected at the counter. The next visit starts with a separate bill.</DialogDescription>{close&&<><p className="pilot-total">Total {money(bill(close).total)}</p><button className="btn" disabled={!!busy} onClick={()=>act(close.id,(config.version||1)>=2?'tfp_settle':'tfp_close',{p_visit:close.id,...((config.version||1)>=2?{p_total:bill(close).total}:{})})}>{busy?'Closing…':'Payment received — close visit'}</button></>}</DialogContent></Dialog>
 </main>
}
